apiVersion: openslo.com/v2alpha1
kind: DataSource
metadata:
  name: cloudWatch-prod
spec:
  description: "CloudWatch Production Data Source"
  cloudWatch:
    accessKeyID: accessKey
    secretAccessKey: secretAccessKey