version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
    open-pull-requests-limit: 2
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
    open-pull-requests-limit: 2
