.DEFAULT_GOAL := help
MAKEFLAGS += --silent --no-print-directory

SCRIPTS_DIR := ./internal/scripts
SDK_PATH ?= ../go-sdk

# Print Makefile target step description for check.
# Only print 'check' steps this way, and not dependent steps, like 'install'.
# ${1} - step description
define _print_step
	printf -- '------\n%s...\n' "${1}"
endef

## Activate developer environment using devbox. Run `make install/devbox` first If you don't have devbox installed.
activate:
	devbox shell

## Install devbox binary.
install/devbox:
	curl -fsSL https://get.jetpack.io/devbox | bash

## Automatically load devbox environment, requires direnv.
direnv:
	devbox generate direnv

.PHONY: check check/style check/spell check/trailing check/markdown check/format check/python check/examples
## Run all checks.
check: check/style website/check check/examples

## Check spelling, whitespace, Markdown, and formatting.
check/style: check/spell check/trailing check/markdown check/format

## Check spelling, rules are defined in cspell.json.
check/spell:
	$(call _print_step,Verifying spelling)
	yarn --silent cspell --no-progress '**/**'

## Check for trailing whitespaces in any of the projects' files.
check/trailing:
	$(call _print_step,Looking for trailing whitespaces)
	$(SCRIPTS_DIR)/check-trailing-whitespaces.bash

## Check markdown files for potential issues with markdownlint.
check/markdown:
	$(call _print_step,Verifying Markdown files)
	yarn --silent markdownlint '**/*.md' --ignore 'node_modules' --ignore 'website'
	yarn --silent markdownlint 'website/**/*.md' --config website/.markdownlint.json --ignore 'website/site*/**'

## Verify if the files are formatted.
## You must first commit the changes, otherwise it won't detect the diffs.
check/format:
	$(call _print_step,Checking if files are formatted)
	$(SCRIPTS_DIR)/check-formatting.sh

## Check Python code.
check/python:
	ruff check website

## Validate complete YAML examples with the pinned SDK.
check/examples:
	cd website/tools/example-check && go test -count=1 ./...

.PHONY: format format/cspell format/python
## Format files.
format: format/cspell format/python

## Format cspell config file.
format/cspell:
	echo "Formatting cspell.yaml configuration (words list)..."
	yarn --silent format-cspell-config

## Format Python files.
format/python:
	ruff format website

.PHONY: website/serve website/build website/check test generate/schema
## Preview the website locally.
website/serve:
	mkdocs serve --config-file website/mkdocs.yml

## Build the website.
website/build:
	mkdocs build --strict --config-file website/mkdocs.yml

## Check website rendering and imports.
website/check: check/python test

## Test website rendering, navigation, and schema imports.
test:
	python -m unittest discover -s website/tests

## Import the manifest generated by the OpenSLO Go SDK.
generate/schema:
	python website/schema.py "$(SDK_PATH)/docs/manifest.json"

.PHONY: install install/yarn install/python
## Install all dev dependencies.
install: install/yarn install/python

## Install JS dependencies with yarn.
install/yarn:
	echo "Installing yarn dependencies..."
	yarn --silent install

## Install Python dependencies into the active environment.
install/python:
	python -m pip install -r website/requirements.txt

.PHONY: help
## Print this help message.
help:
	$(SCRIPTS_DIR)/makefile-help.awk $(MAKEFILE_LIST)
