authors:
  Mateusz Hawrus:
    name: Mateusz Hawrus
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/48822818?v=4
    url: https://github.com/nieomylnieja/
  Filip Piwowarczyk:
    name: Filip Piwowarczyk
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/29290009?v=4
    url: https://github.com/fpiwowarczyk
  Pawel Rusakiewicz:
    name: Pawel Rusakiewicz
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/85633588?v=4
    url: https://github.com/pawel-nobl9
