apiVersion: openslo/v1
kind: DataSource
metadata:
  name: test-data-source
  displayName: Test Data Source
spec:
  type: CloudWatch
  connectionDetails:
    accessKeyID: accessKey
    secretAccessKey: secretAccessKey
