//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v2alpha

import (
	"encoding/json"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertCondition) DeepCopyInto(out *AlertCondition) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertCondition.
func (in *AlertCondition) DeepCopy() *AlertCondition {
	if in == nil {
		return nil
	}
	out := new(AlertCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertConditionSpec) DeepCopyInto(out *AlertConditionSpec) {
	*out = *in
	in.Condition.DeepCopyInto(&out.Condition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertConditionSpec.
func (in *AlertConditionSpec) DeepCopy() *AlertConditionSpec {
	if in == nil {
		return nil
	}
	out := new(AlertConditionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertConditionType) DeepCopyInto(out *AlertConditionType) {
	*out = *in
	if in.Threshold != nil {
		in, out := &in.Threshold, &out.Threshold
		*out = new(float64)
		**out = **in
	}
	out.LookbackWindow = in.LookbackWindow
	out.AlertAfter = in.AlertAfter
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertConditionType.
func (in *AlertConditionType) DeepCopy() *AlertConditionType {
	if in == nil {
		return nil
	}
	out := new(AlertConditionType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertNotificationTarget) DeepCopyInto(out *AlertNotificationTarget) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertNotificationTarget.
func (in *AlertNotificationTarget) DeepCopy() *AlertNotificationTarget {
	if in == nil {
		return nil
	}
	out := new(AlertNotificationTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertNotificationTargetSpec) DeepCopyInto(out *AlertNotificationTargetSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertNotificationTargetSpec.
func (in *AlertNotificationTargetSpec) DeepCopy() *AlertNotificationTargetSpec {
	if in == nil {
		return nil
	}
	out := new(AlertNotificationTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertPolicy) DeepCopyInto(out *AlertPolicy) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertPolicy.
func (in *AlertPolicy) DeepCopy() *AlertPolicy {
	if in == nil {
		return nil
	}
	out := new(AlertPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertPolicyCondition) DeepCopyInto(out *AlertPolicyCondition) {
	*out = *in
	if in.AlertPolicyConditionRef != nil {
		in, out := &in.AlertPolicyConditionRef, &out.AlertPolicyConditionRef
		*out = new(AlertPolicyConditionRef)
		**out = **in
	}
	if in.AlertPolicyConditionInline != nil {
		in, out := &in.AlertPolicyConditionInline, &out.AlertPolicyConditionInline
		*out = new(AlertPolicyConditionInline)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertPolicyCondition.
func (in *AlertPolicyCondition) DeepCopy() *AlertPolicyCondition {
	if in == nil {
		return nil
	}
	out := new(AlertPolicyCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertPolicyConditionInline) DeepCopyInto(out *AlertPolicyConditionInline) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertPolicyConditionInline.
func (in *AlertPolicyConditionInline) DeepCopy() *AlertPolicyConditionInline {
	if in == nil {
		return nil
	}
	out := new(AlertPolicyConditionInline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertPolicyConditionRef) DeepCopyInto(out *AlertPolicyConditionRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertPolicyConditionRef.
func (in *AlertPolicyConditionRef) DeepCopy() *AlertPolicyConditionRef {
	if in == nil {
		return nil
	}
	out := new(AlertPolicyConditionRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertPolicyNotificationTarget) DeepCopyInto(out *AlertPolicyNotificationTarget) {
	*out = *in
	if in.AlertPolicyNotificationTargetRef != nil {
		in, out := &in.AlertPolicyNotificationTargetRef, &out.AlertPolicyNotificationTargetRef
		*out = new(AlertPolicyNotificationTargetRef)
		**out = **in
	}
	if in.AlertPolicyNotificationTargetInline != nil {
		in, out := &in.AlertPolicyNotificationTargetInline, &out.AlertPolicyNotificationTargetInline
		*out = new(AlertPolicyNotificationTargetInline)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertPolicyNotificationTarget.
func (in *AlertPolicyNotificationTarget) DeepCopy() *AlertPolicyNotificationTarget {
	if in == nil {
		return nil
	}
	out := new(AlertPolicyNotificationTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertPolicyNotificationTargetInline) DeepCopyInto(out *AlertPolicyNotificationTargetInline) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertPolicyNotificationTargetInline.
func (in *AlertPolicyNotificationTargetInline) DeepCopy() *AlertPolicyNotificationTargetInline {
	if in == nil {
		return nil
	}
	out := new(AlertPolicyNotificationTargetInline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertPolicyNotificationTargetRef) DeepCopyInto(out *AlertPolicyNotificationTargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertPolicyNotificationTargetRef.
func (in *AlertPolicyNotificationTargetRef) DeepCopy() *AlertPolicyNotificationTargetRef {
	if in == nil {
		return nil
	}
	out := new(AlertPolicyNotificationTargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertPolicySpec) DeepCopyInto(out *AlertPolicySpec) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]AlertPolicyCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NotificationTargets != nil {
		in, out := &in.NotificationTargets, &out.NotificationTargets
		*out = make([]AlertPolicyNotificationTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertPolicySpec.
func (in *AlertPolicySpec) DeepCopy() *AlertPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AlertPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Annotations) DeepCopyInto(out *Annotations) {
	{
		in := &in
		*out = make(Annotations, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Annotations.
func (in Annotations) DeepCopy() Annotations {
	if in == nil {
		return nil
	}
	out := new(Annotations)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSource) DeepCopyInto(out *DataSource) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSource.
func (in *DataSource) DeepCopy() *DataSource {
	if in == nil {
		return nil
	}
	out := new(DataSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceSpec) DeepCopyInto(out *DataSourceSpec) {
	*out = *in
	if in.ConnectionDetails != nil {
		in, out := &in.ConnectionDetails, &out.ConnectionDetails
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceSpec.
func (in *DataSourceSpec) DeepCopy() *DataSourceSpec {
	if in == nil {
		return nil
	}
	out := new(DataSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DurationShorthand) DeepCopyInto(out *DurationShorthand) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DurationShorthand.
func (in *DurationShorthand) DeepCopy() *DurationShorthand {
	if in == nil {
		return nil
	}
	out := new(DurationShorthand)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Labels) DeepCopyInto(out *Labels) {
	{
		in := &in
		*out = make(Labels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Labels.
func (in Labels) DeepCopy() Labels {
	if in == nil {
		return nil
	}
	out := new(Labels)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Metadata) DeepCopyInto(out *Metadata) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(Labels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(Annotations, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Metadata.
func (in *Metadata) DeepCopy() *Metadata {
	if in == nil {
		return nil
	}
	out := new(Metadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLI) DeepCopyInto(out *SLI) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLI.
func (in *SLI) DeepCopy() *SLI {
	if in == nil {
		return nil
	}
	out := new(SLI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLIMetricSpec) DeepCopyInto(out *SLIMetricSpec) {
	*out = *in
	if in.DataSourceSpec != nil {
		in, out := &in.DataSourceSpec, &out.DataSourceSpec
		*out = new(DataSourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = make(json.RawMessage, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLIMetricSpec.
func (in *SLIMetricSpec) DeepCopy() *SLIMetricSpec {
	if in == nil {
		return nil
	}
	out := new(SLIMetricSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLIRatioMetric) DeepCopyInto(out *SLIRatioMetric) {
	*out = *in
	if in.Good != nil {
		in, out := &in.Good, &out.Good
		*out = new(SLIMetricSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Bad != nil {
		in, out := &in.Bad, &out.Bad
		*out = new(SLIMetricSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Total != nil {
		in, out := &in.Total, &out.Total
		*out = new(SLIMetricSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Raw != nil {
		in, out := &in.Raw, &out.Raw
		*out = new(SLIMetricSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLIRatioMetric.
func (in *SLIRatioMetric) DeepCopy() *SLIRatioMetric {
	if in == nil {
		return nil
	}
	out := new(SLIRatioMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLISpec) DeepCopyInto(out *SLISpec) {
	*out = *in
	if in.ThresholdMetric != nil {
		in, out := &in.ThresholdMetric, &out.ThresholdMetric
		*out = new(SLIMetricSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RatioMetric != nil {
		in, out := &in.RatioMetric, &out.RatioMetric
		*out = new(SLIRatioMetric)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLISpec.
func (in *SLISpec) DeepCopy() *SLISpec {
	if in == nil {
		return nil
	}
	out := new(SLISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLO) DeepCopyInto(out *SLO) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLO.
func (in *SLO) DeepCopy() *SLO {
	if in == nil {
		return nil
	}
	out := new(SLO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOAlertPolicy) DeepCopyInto(out *SLOAlertPolicy) {
	*out = *in
	if in.SLOAlertPolicyInline != nil {
		in, out := &in.SLOAlertPolicyInline, &out.SLOAlertPolicyInline
		*out = new(SLOAlertPolicyInline)
		(*in).DeepCopyInto(*out)
	}
	if in.SLOAlertPolicyRef != nil {
		in, out := &in.SLOAlertPolicyRef, &out.SLOAlertPolicyRef
		*out = new(SLOAlertPolicyRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOAlertPolicy.
func (in *SLOAlertPolicy) DeepCopy() *SLOAlertPolicy {
	if in == nil {
		return nil
	}
	out := new(SLOAlertPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOAlertPolicyInline) DeepCopyInto(out *SLOAlertPolicyInline) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOAlertPolicyInline.
func (in *SLOAlertPolicyInline) DeepCopy() *SLOAlertPolicyInline {
	if in == nil {
		return nil
	}
	out := new(SLOAlertPolicyInline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOAlertPolicyRef) DeepCopyInto(out *SLOAlertPolicyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOAlertPolicyRef.
func (in *SLOAlertPolicyRef) DeepCopy() *SLOAlertPolicyRef {
	if in == nil {
		return nil
	}
	out := new(SLOAlertPolicyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOCalendar) DeepCopyInto(out *SLOCalendar) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOCalendar.
func (in *SLOCalendar) DeepCopy() *SLOCalendar {
	if in == nil {
		return nil
	}
	out := new(SLOCalendar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOObjective) DeepCopyInto(out *SLOObjective) {
	*out = *in
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(float64)
		**out = **in
	}
	if in.TargetPercent != nil {
		in, out := &in.TargetPercent, &out.TargetPercent
		*out = new(float64)
		**out = **in
	}
	if in.TimeSliceTarget != nil {
		in, out := &in.TimeSliceTarget, &out.TimeSliceTarget
		*out = new(float64)
		**out = **in
	}
	if in.TimeSliceWindow != nil {
		in, out := &in.TimeSliceWindow, &out.TimeSliceWindow
		*out = new(DurationShorthand)
		**out = **in
	}
	if in.SLI != nil {
		in, out := &in.SLI, &out.SLI
		*out = new(SLOSLIInline)
		(*in).DeepCopyInto(*out)
	}
	if in.SLIRef != nil {
		in, out := &in.SLIRef, &out.SLIRef
		*out = new(string)
		**out = **in
	}
	if in.CompositeWeight != nil {
		in, out := &in.CompositeWeight, &out.CompositeWeight
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOObjective.
func (in *SLOObjective) DeepCopy() *SLOObjective {
	if in == nil {
		return nil
	}
	out := new(SLOObjective)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOSLIInline) DeepCopyInto(out *SLOSLIInline) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOSLIInline.
func (in *SLOSLIInline) DeepCopy() *SLOSLIInline {
	if in == nil {
		return nil
	}
	out := new(SLOSLIInline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOSpec) DeepCopyInto(out *SLOSpec) {
	*out = *in
	if in.SLI != nil {
		in, out := &in.SLI, &out.SLI
		*out = new(SLOSLIInline)
		(*in).DeepCopyInto(*out)
	}
	if in.SLIRef != nil {
		in, out := &in.SLIRef, &out.SLIRef
		*out = new(string)
		**out = **in
	}
	if in.TimeWindow != nil {
		in, out := &in.TimeWindow, &out.TimeWindow
		*out = make([]SLOTimeWindow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Objectives != nil {
		in, out := &in.Objectives, &out.Objectives
		*out = make([]SLOObjective, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AlertPolicies != nil {
		in, out := &in.AlertPolicies, &out.AlertPolicies
		*out = make([]SLOAlertPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOSpec.
func (in *SLOSpec) DeepCopy() *SLOSpec {
	if in == nil {
		return nil
	}
	out := new(SLOSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOTimeWindow) DeepCopyInto(out *SLOTimeWindow) {
	*out = *in
	out.Duration = in.Duration
	if in.Calendar != nil {
		in, out := &in.Calendar, &out.Calendar
		*out = new(SLOCalendar)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOTimeWindow.
func (in *SLOTimeWindow) DeepCopy() *SLOTimeWindow {
	if in == nil {
		return nil
	}
	out := new(SLOTimeWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Service) DeepCopyInto(out *Service) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Service.
func (in *Service) DeepCopy() *Service {
	if in == nil {
		return nil
	}
	out := new(Service)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpec.
func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}
