apiVersion: openslo/v1
kind: SLI
metadata:
  name: great-sli
  displayName: Great SLI
spec:
  description: This is an amazing description of the best SLI
  thresholdMetric:
    metricSource:
      metricSourceRef: redshift-datasource
      spec:
        region: eu-central-1
        clusterId: metrics-cluster
        databaseName: metrics-db
        query: SELECT value, timestamp FROM metrics WHERE timestamp BETWEEN :date_from AND :date_to
