apiVersion: openslo/v1
kind: AlertPolicy
metadata:
  name: alert-policy
  displayName: Alert Policy
spec:
  description: Alert policy for cpu usage breaches, notifies on-call devops via email
  alertWhenBreaching: true
  alertWhenResolved: false
  alertWhenNoData: false
  conditions:
    - operator: and
      conditionRef: cpu-usage-breach
  notificationTargets:
    - targetRef: on-call-devops-mail-notification
    - targetRef: on-call-devops-mail-notification
    - targetRef: on-call-devops-mail-notification
    - targetRef: on-call-devops-mail-notification
    - targetRef: on-call-devops-mail-notification
    - targetRef: on-call-devops-mail-notification
    - targetRef: on-call-devops-mail-notification
