apiVersion: openslo/v1
kind: AlertCondition
metadata:
  name: alert-condition
  displayName: Alert Condition
spec:
  description: A great description # optional up to 1050 characters
  severity: sev1 # required
