import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parent


def main():
    parser = argparse.ArgumentParser(description="Import the upstream specification.")
    parser.add_argument("readme", type=Path)
    args = parser.parse_args()
    source = args.readme.read_text(encoding="utf-8")
    _, marker, content = source.partition("## Introduction\n")
    if not marker or "## Specification\n" not in content:
        parser.error(
            "The source README must contain Introduction and Specification sections"
        )
    content = marker + content
    for kind in ("DataSource", "SLO", "SLI"):
        slug = kind.lower()
        old = f"> [Check work in progress for v2.](enhancements/v2alpha.md#{slug})"
        if old not in content:
            parser.error(f"The source README is missing the {kind} draft link")
        replacement = (
            f"> [See the v1 {kind} reference.](schema/v1/{slug}.md)\n>\n"
            "> [View the v2 draft.]"
            f"(https://github.com/OpenSLO/OpenSLO/blob/main/enhancements/v2alpha.md#{slug})"
        )
        if kind == "SLO":
            replacement += (
                '\n\n!!! note "Go SDK validation"\n\n'
                "    The v1 specification makes `timeWindow` optional.\n"
                "    The Go SDK currently requires exactly one time window.\n"
                "    Include a window when validating an SLO with the SDK."
            )
        content = content.replace(old, replacement)
    content = content.replace(
        "](CONTRIBUTING.md)",
        "](https://github.com/OpenSLO/OpenSLO/blob/main/CONTRIBUTING.md)",
    )
    content = (
        "<!-- Generated by specification.py from OpenSLO/OpenSLO README.md. -->\n\n"
        "# Specification\n\n"
        + content
    )
    (ROOT / "docs/specification.md").write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
