name: Run checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install devbox
        uses: jetify-com/devbox-install-action@8c6a66ed6273138b1915457069de78cb52fe3bd7 # v0.15.0
        with:
          devbox-version: 0.18.3
          enable-cache: true
      - name: Run checks
        run: devbox run -- make check/style
