name: spell-and-markdown-checks
on:
  pull_request:
jobs:
  check:
    name: Check all files spelling and markdown files formatting
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up prerequisites - node and yarn
        uses: actions/setup-node@v3
      - name: Set up yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install spell and markdown checkers
        run: |
          make install/checks/spell-and-markdown
      - name: Run spell and markdown checkers
        run: |
          make run/checks/spell-and-markdown
